### ISSUE TITLE
Can't change gdb's prompt

### ISSUE THREAD

**Issue by Charo-IT** [david942j/gdb-ruby#2]
It seems that "set prompt" command is ignored in gdb-ruby.

On gdb:
```
# gdb -q
(gdb) set prompt gdb> 
gdb> show prompt
Gdb's prompt is "gdb> ".
gdb> quit
```
On gdb-ruby (0.2.0):
```
# gdb-ruby -q
(gdb) set prompt gdb> 
(gdb) show prompt
Gdb's prompt is "(gdb) ".
(gdb) quit
```

**Comment by david942j** [comment]
I'll fix it, but currently you can add this line in your `.gdbinit` to reach what you want:
`python gdb.prompt_hook = lambda _: 'gdb> '`
then
```
$ gdb-ruby -q
gdb> 
```

**Comment by Charo-IT** [comment]
Thanks for workaround!
