### ISSUE TITLE
IO.console is only available in terminals

### ISSUE THREAD

**Issue by trialism** [david942j/gdb-ruby#21]
Hi,

https://github.com/david942j/gdb-ruby/blob/e11c8ce725d3ce7f089422c280136a364dd9e50b/lib/gdb/gdb.rb#L316

The line above makes gdb-ruby impossible to use in GUI and daemon apps.

**Comment by david942j** [comment]
Thanks for pointing out this!
Could you also give an example usage (command of GUI/daemon) so that I can check if I do fix the issue?

**Comment by stevendobay** [comment]
I'd recommend [neovim-qt](https://github.com/equalsraf/neovim-qt) with [neovim-ruby](https://github.com/alexgenco/neovim-ruby). Calling `GDB::GDB.new()` is enough. Thanks!
